#simple version
version: "3.5"


# Указываем сеть 'localhost' в которой будут общаться контейнеры Сети можно дать имя чтобы было удобно смотреть при проверке работы сети
#вообще сети в Docker Compose создается по умолчанию и не прописывается в явном виде
#cетей может быть несколько и каждому контейнеру можно указывать отдельные сети чтобы контейнеры не могли общаться друг с другом
#больше информации смотри в документации на сайте Docker Compose: https://docs.docker.com/compose/networking/
networks: 
        localhost: 
                name: inet



# в volumes сеть не указывается 
volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/areggie/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/areggie/data/mariadb
                        o: bind
                        type: none



#3 контейнера: nginx, mariadb, wordpress общаются в одной сети "localhost" (имя в ней уже есть и здесь оно не упоманиается)
services:
        nginx:
                depends_on:
                        - wordpress
                container_name: nginx_debian
                build: ./nginx
                image: nginx
                ports:
                        - "443:443"
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - localhost
                restart: always
        mariadb:  
                container_name: mariadb_debian
                build: ./mariadb
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - localhost
                image: mariadb
                restart: always
        wordpress:
                depends_on:
                        - mariadb
                container_name: wordpress_debian
                build: ./wordpress
                image: wordpress
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - localhost
                restart: always