FROM debian:buster
MAINTAINER areggie <areggie@student.21-school.ru>

RUN apt-get update 
RUN apt-get install -y mariadb-server vim

COPY ./50-server.cnf /etc/mysql/mariadb.conf.d/
COPY db.sh      /var/www/
RUN chmod 444 /etc/mysql/mariadb.conf.d/50-server.cnf
RUN chmod 755 /var/www/db.sh 

EXPOSE 3306
ENTRYPOINT ["bash", "/var/www/db.sh"]
